### PR TITLE
untracked movie functionality

### PR DESCRIPTION
**Pull request by markellisdev**
Ahh, success. Went back to master and retyped. Must've missed something in the earlier PR, but this one is good. Please take a look.

### CODE REVIEW

**Review by stevenwally — APPROVED** [review]
looks good, mark 👍

**Comment by markellisdev** [comment]
Please take a look at the updated version. I'm awaiting Steve's answers to our questions. He has us on his list.
I linked up `getMovies()` and have the landing page loading with movies, which I changed to Batman search page 2, because it gave no 404 image errors like page 3 was. I've hidden the other spans (breadcrumbs) for the Untracked page. Happy Thanksgiving everyone!

**Comment by sales-ls21** [comment]
Just to confirm: when the user searches and the page populates, are we highlighting the untracked button or are we waiting until the user clicks on the untracked button? I, for some reason, can't see the functionality when I checkout your branch. If we can get the untracked button to highlight when the search is submitted and the breadcrumbs to reflect that we are only showing the search results, that would be awesome. Also, are we hiding the buttons on page load, since we presume the user isn't logged in immediately? Maybe we write a function that checks and either shows the buttons or not, depending on if the user is logged in or not. If someone else can confirm that the functionality works like that and can give Mark the thumbs up, we'd be good to have a new master. Thanks!

**Comment by markellisdev** [comment]
Currently the `Untracked` button only highlights when the User clicks it.

The breadcrumbs are currently showing `Search Results` only.

We don't currently hide the buttons on page load, but I can do that as well.

**Comment by sales-ls21** [comment]
Mark, check out my slack comments and let me know if that makes sense

**Comment by markellisdev** [comment]
LaDonna,
I read your comments and they definitely made sense. I went through and corrected everything. Please double check my work though of course. ;-) I also corrected a spelling error we had in `onload.hbs`. This latest commit reflects those changes.
Hope you're having a great night with family!

**Comment by sales-ls21** [comment]
Looks good. Go ahead and merge and I'll try to get the watched and unwatched loaded up later today.

**Pull request merged**
